% matutils – Peter Jacklam mattix utilities  
% acoshplus1.m           
% acosplus1.m            
% ascol.m                
% asrow.m                
% asvec.m                
% atanminuspihalf.m      
% blockdiag.m            
% blockflipdim.m         
% blockfliplr.m          
% blockflipud.m          
% blockrot90.m           
% bounds2ind.m           
% coshminus1.m           
% cosminus1.m            
% cropbyval.m            
% cummax.m               
% distmat.m              
% distmat0.m             
% distmat1.m             
% distmat2.m             
% distmat3.m         
% findrows.m         
% flipalldims.m   
% fmap.m          
% fnsdim.m        
% gsexpand.m      
% isalnum.m       
% isalpha.m       
% isascii.m       
% iscolvector.m   
% isdigit.m       
% iseven.m        
% isint.m         
% islower.m       
% ismatrix.m      
% isodd.m         
% isposint.m      
% isprtchr.m      
% isrowvector.m   
% isscalarBis.m   
% issymmetric.m   
% isupper.m       
% isvectorBIS.m   
% isxdigit.m      
% mahaldist.m      
% maskrepelem.m    
% mergearray.m     
% movsum.m         
% ndimgrid.m       
% powerset.m       
% reparray.m       
% repelm.m         
% resize.m         
% rotarray.m       
% sexpand.m        
% sinc.m           
% splitarray.m     
% subdivide.m      
% swapdims.m       
% tanhminus1.m     
% tanpluspihalf.m  
% vecfill.m        
% wraprad.m        
% xkron.m          
% xrepmat.m        
% zeroscls.m       
